# version:     "0026--06-Sep-2022"
copyright:   "2022"
author:      "JonathanAdriell"
name:        "Jonathan Adriel"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/JonathanAdriell/os222"
myloglink:   "/TXT/mylog.txt"
tarballlink: "https://os.vlsm.org/Log/JonathanAdriell.tar.bz2.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
